// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0NR-KixYyATz9icsU2ZR5ApNNGjbT5gU',
    appId: '1:179857872573:web:f159849c150c5111fcc9d4',
    messagingSenderId: '179857872573',
    projectId: 'sahayi-29347',
    authDomain: 'sahayi-29347.firebaseapp.com',
    storageBucket: 'sahayi-29347.appspot.com',
    measurementId: 'G-8FL7W24NEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP13kqCEgMDXTBcoSSHMzmRv25jVy8d4U',
    appId: '1:179857872573:android:62eef047ed5e8cbffcc9d4',
    messagingSenderId: '179857872573',
    projectId: 'sahayi-29347',
    storageBucket: 'sahayi-29347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUGM2dNdR6LEgI54KYa5JLXBgcbdMJZJ4',
    appId: '1:179857872573:ios:4a07ca48ee84521dfcc9d4',
    messagingSenderId: '179857872573',
    projectId: 'sahayi-29347',
    storageBucket: 'sahayi-29347.appspot.com',
    iosBundleId: 'com.example.townPmnaV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUGM2dNdR6LEgI54KYa5JLXBgcbdMJZJ4',
    appId: '1:179857872573:ios:4a07ca48ee84521dfcc9d4',
    messagingSenderId: '179857872573',
    projectId: 'sahayi-29347',
    storageBucket: 'sahayi-29347.appspot.com',
    iosBundleId: 'com.example.townPmnaV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0NR-KixYyATz9icsU2ZR5ApNNGjbT5gU',
    appId: '1:179857872573:web:8ea6495dec14d758fcc9d4',
    messagingSenderId: '179857872573',
    projectId: 'sahayi-29347',
    authDomain: 'sahayi-29347.firebaseapp.com',
    storageBucket: 'sahayi-29347.appspot.com',
    measurementId: 'G-BW7FXXK4NN',
  );
}